# Numpy Tasks

## Task_1

#### Question 1. Create a numpy array with 6X5 2D array from 10 upwards

In [25]:
import numpy as np
my_array = np.arange(10, 69, 2).reshape(6,5)
my_array

array([[10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48],
       [50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68]])

#### Question 2. From question 1, reshape the numpy array to any shape of your choice and return the max value from each column.

In [33]:
reshaped_arr = my_array.reshape(-1, 6)
print(reshaped_arr)
max_val_col1 = reshaped_arr.max(axis=0)
print('\nMaximum of Each Column ==>', max_val_col1)

[[10 12 14 16 18 20]
 [22 24 26 28 30 32]
 [34 36 38 40 42 44]
 [46 48 50 52 54 56]
 [58 60 62 64 66 68]]

Maximum of Each Column==> [58 60 62 64 66 68]


#### Question 3. Create a numpy array A with np.ones with a shape of (3,4). Create another array using the np.arange with a shape of (3,4). 

In [37]:
A = np.ones((3, 4))
print(A)
B = np.arange(2, 25, 2).reshape(3, 4)
print()
print(B)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]


#### Question 4. Perform arithmetic operations (+,-,*,/) on the two arrays from question 3.

In [40]:
addition = A+B
subtraction = A-B
multiplication = A*B
division = A/B

print('Addition ==> \n', addition)
print('Subtraction ==> \n', subtraction)
print('Multiplication ==> \n', multiplication)
print('Division ==> \n', division)

Addition ==> 
 [[ 3.  5.  7.  9.]
 [11. 13. 15. 17.]
 [19. 21. 23. 25.]]
Subtraction ==> 
 [[ -1.  -3.  -5.  -7.]
 [ -9. -11. -13. -15.]
 [-17. -19. -21. -23.]]
Multiplication ==> 
 [[ 2.  4.  6.  8.]
 [10. 12. 14. 16.]
 [18. 20. 22. 24.]]
Division ==> 
 [[0.5        0.25       0.16666667 0.125     ]
 [0.1        0.08333333 0.07142857 0.0625    ]
 [0.05555556 0.05       0.04545455 0.04166667]]


#### Question 5. From question 4, transpose the results of each arithmetic operation.

In [44]:
addition_transpose = addition.T
subtraction_transpose = subtraction.T
multiplication_transpose = multiplication.T
division_transpose = division.T

print('Additon Transpose\n', addition_transpose)
print('Subtraction Transpose\n', subtraction_transpose)
print('Muk Transpose\n', multiplication_transpose)
print(division_transpose)

[[ 3. 11. 19.]
 [ 5. 13. 21.]
 [ 7. 15. 23.]
 [ 9. 17. 25.]]
[[ -1.  -9. -17.]
 [ -3. -11. -19.]
 [ -5. -13. -21.]
 [ -7. -15. -23.]]
[[ 2. 10. 18.]
 [ 4. 12. 20.]
 [ 6. 14. 22.]
 [ 8. 16. 24.]]
[[0.5        0.1        0.05555556]
 [0.25       0.08333333 0.05      ]
 [0.16666667 0.07142857 0.04545455]
 [0.125      0.0625     0.04166667]]
